config/routes.rb
Rails.application.routes.draw do
	default_url_options :host => "example.com"

	devise_for :users, path: '',
	 controllers: {
			 registrations: 'registrations',
			 omniauth_callbacks: 'users/omniauth_callbacks'
	 }

	get '/users/developers', to: 'users#index', as: :developers

	resources :users, only: [:show, :edit, :update, :index]

	resources :conversations, only: [:index, :create] do
		resources :messages, only: [:index, :new, :create]
	end

	resources :projects, only: [:show, :index, :new, :create, :edit, :update]

	# root to: 'static#home'
	root to: redirect("/sign_in")

	get '/welcome', to: 'static#welcome'


	# routes
	# new_user_session 				GET    /sign_in(.:format)       devise/sessions#new
	# user_session 						POST   /sign_in(.:format)       devise/sessions#create
	# destroy_user_session 		DELETE /sign_out(.:format)      devise/sessions#destroy
	# new_user_registration 	GET    /sign_up(.:format)       registrations#new

end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :author, foreign_key: :author_id, class_name: "User"
	has_many :project_skills, foreign_key: :skill_id
	# accepts_nested_attributes_for :project_skills

	validates_presence_of :title, :description

	def project_skills_attributes=(skills_attributes)
		self.save
		skills_attributes.values.each do |skill_attribute|
			if skill_attribute[:title].present?
				self.project_skills.create(skill_attribute)
			end
		end
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:show, :edit, :update]

	def index
		@projects = Project.order("created_at DESC")
	end

	def show
		@skills = @project.project_skills
		@author = @project.author
    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
	end

	def new
		@project = Project.new
		@project.project_skills.build
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			redirect_to projects_path, notice: "New project added"
		else
			render :new
		end
	end

	def edit
		if current_user != @project.author
			redirect_to welcome_path, alert: "Access denied"
		end
	end

	def update
		if current_user == @project.author
			if @project.update(project_params)
				redirect_to project_path(@project), notice: "Project successfully updated"
			else
				render :edit
			end
		else
			redirect_to welcome_path, alert: "Access denied"
		end
	end

	private
		def set_project
			@project = Project.find(params[:id])
		end

		def project_params
			params.require(:project).permit(
					:title,
					:description,
					:author_id,
					project_skills_attributes: [
							:title,
							:description
					]
			)
		end
end

app/helpers/project_helper.rb
module ProjectHelper

  def prev_project_link(id)
    prev_id = id - 1;
    if(prev_id > 0)
      link_to 'Previous', project_path(prev_id), id: "load-prev-project"
    end
  end

	def next_project_link(id)
    next_id = id + 1;
    if(next_id <= Project.count)
      link_to 'Next', project_path(next_id), id: "load-next-project"
    end
  end
end

app/views/projects/_form.html.erb
<%= form_for project do |f| %>
	<%= render partial: 'shared/errors', locals: {obj: project} %>

	<fieldset class="general">
		<legend>Describe the project</legend>
		<%= render partial: "shared/text_field", locals: {builder: f, prop: :title} %>
		<%= render partial: 'shared/text_area', locals: {builder: f, prop: :description} %>

		<%= f.hidden_field :author_id, value: "#{current_user.id}" %>
	</fieldset>

	<fieldset class="skills">
		<legend>Add a skill(optional)</legend>
		<div class="skill">
			<%= f.fields_for :project_skills do |builder| %>
				<%= render partial: 'project_skill_field', locals: {f: builder} %>
			<% end %>

			<div class="control-group">
				<%= add_another_field 'Add Skill', f, :project_skills %>
			</div>
		</div>
	</fieldset>

	<%= f.submit 'Create Project', class: "btn btn-info" %>
<% end %>

app/views/projects/_project_skill_field.html.erb
<%= render partial: 'shared/text_field', locals: {builder: f, prop: :title} %>
<%= render partial: 'shared/text_area', locals: {builder: f, prop: :description} %>

app/views/projects/edit.html.erb
<h1>Edit project</h1>

app/views/projects/index.html.erb
<div class="content-wrap">
	<h1 class="page-title">Current projects</h1>

	<%= link_to 'Add a new project', new_project_path, class: "page-link" %>

	<% if @projects.count > 0 %>
		<ul class="items opportunities">
			<% @projects.each do |project| %>
				<li class="item project">
					<div class="contents-wrap clearfix">

						<div class="profile">
							<div class="image">
								<%= image_tag user_avatar(project.author.main_image), class: 'circle' %>
							</div>
							<div class="details">
								<h3><%= link_to project.author.name.upcase, user_path(project.author) %></h3>
								<p><%= project.author.email %></p>
								<% if project.author.social_links.count > 0 %>
									<div>
										<% project.author.social_links.each do |link| %>
											<%= link_to link.url, target: "_blank", class: "link_icon" do %>
												<i class="fa fa-2x fa-<%= link.name.downcase %>"></i>
											<% end %>
										<% end %>
									</div>
								<% end %>
							</div>
						</div>

						<div class="contents">
							<p class="title"><%= project.title %></p>
							<div class="description-wrap">
								<p class="description">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
									<%= project.description[0..200] %>...
									<i class="fa fa-quote-right" aria-hidden="true"></i>
								</p>
								<%= link_to "Read more", project_path(project)  %>
							</div>
						</div>

					</div>
				</li>
			<% end %>
		</ul>
	<% end %>
</div>

app/views/projects/new.html.erb
<div class="content-wrap">

	<h1 class="page-title">Create a new project</h1>


	<%= link_to "Back to projects", projects_path, class: 'page-link' %>


	<%= render partial: 'form', locals: {project: @project, skill: @skill} %>

</div>

app/views/projects/show.html.erb
<div class="content-wrap">

	<div class="project-wrap">
		<div class="project">
	    <h2 class="page-title"><%= @project.title %></h2>
			<p><%= @project.description %></p>

			<% if @skills.count > 0 %>
				<h3>You will have the following capabilities</h3>
				<dl class="items skills">
					<% @skills.each do |skill| %>
						<dt class="skill-title"><%= skill.title %></dt>
						<dd class="skill-description"><%= skill.description %></dd>
					<% end %>
				</dl>
			<% end %>
		</div>

		<div class="author-details">
			<div class="image">
				<%= image_tag user_avatar(@author.main_image), class: "circle" %>
			</div>
			<% if current_user != @author %>
				<div class="author-links clearfix">
					<p>Check <%= link_to "#{@author.name}'s", user_path(@author) %> profile</p>

						<span>&nbsp;or </span>
						<%= form_tag conversations_path, method: 'post' do %>
							<%= hidden_field_tag :title, value = @project.title  %>
							<%= hidden_field_tag :recipient_id, value = @author.id %>
							<%= submit_tag "start a conversation", class: "btn-conversation"	%>
					<% end %>
				</div>
			<% end %>
		</div>

		<div id="project-nav" class="clearfix">
    	<%= next_project_link(@project.id) %>
    	<%= prev_project_link(@project.id) %>
		</div>
	</div>

	<%= link_to "Back to projects", projects_path, class: "page-link-bottom" %>
</div>