config/routes.rb
Rails.application.routes.draw do
	default_url_options :host => "example.com"

	devise_for :users, path: '',
	 controllers: {
			 registrations: 'registrations',
			 omniauth_callbacks: 'users/omniauth_callbacks'
	 }

	get '/users/developers', to: 'users#index', as: :developers

	resources :users, only: [:show, :edit, :update, :index]

	resources :conversations, only: [:index, :create] do
		resources :messages, only: [:index, :new, :create]
	end

	resources :projects, only: [:show, :index, :new, :create, :edit, :update]

	# root to: 'static#home'
	root to: redirect("/sign_in")

	get '/welcome', to: 'static#welcome'


	# routes
	# new_user_session 				GET    /sign_in(.:format)       devise/sessions#new
	# user_session 						POST   /sign_in(.:format)       devise/sessions#create
	# destroy_user_session 		DELETE /sign_out(.:format)      devise/sessions#destroy
	# new_user_registration 	GET    /sign_up(.:format)       registrations#new

end

app/views/layouts/_flash.html.erb
<% if flash.any? %>
	<div class="row">
		<div class="col-xs-12">
			<% flash.each do |name, message| %>
				<div class="alert alert-<%= name == 'notice' ? 'success' : 'warning' %> alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<%= message %>
				</div>
			<% end %>
		</div>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="text-muted">
	<div class="container">
		<p>Copyright &copy; <%= Time.now.year %> FindADev</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= home_link %>
		</div>
		<div class="navbar-collapse collapse">
			<%= render 'layouts/main_nav' %>
			<%= render 'layouts/right_nav' %>
		</div><!--/.nav-collapse -->
	</div>
</div>

app/views/layouts/_main_nav.html.erb
<ul class="nav navbar-nav">
	<li><%= link_to "Developers", developers_path %></li>
	<li><%= link_to 'Projects', projects_path %></li>
</ul>

app/views/layouts/_right_nav.erb
<ul class="nav navbar-nav navbar-right">
	<% if user_signed_in? %>
		<li><%= link_to "Your conversations", conversations_path %></li>
		<li><%= link_to "Your profile", user_path(current_user) %></li>
		<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
	<% else %>
		<li><%= link_to "Sign up", new_user_registration_path %></li>
		<li><%= link_to "Sign in", new_user_session_path %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindADev</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%#= javascript_include_tag 'application' %>
		<%= csrf_meta_tags %>
		<%= analytics_init if Rails.env.production? %>
  </head>

  <body data-useremail="<%= current_user.email %>" data-projectcount=<%= Project.count %>">
		<%= render 'layouts/header' %>
		<div id="container" class="container">
			<%= render "layouts/flash" %>

			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>FindADev</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
	<%= csrf_meta_tags %>
	<%= analytics_init if Rails.env.production? %>
</head>

<body id="devise">

	<div class="container">
		<%= render 'layouts/flash' %>
		<%= devise_error_messages! %>

		<div class="devise">
			<%= yield %>
		</div>

	</div>
</body>
</html>